//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/QTEInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @QTEInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @QTEInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""QTEInputActions"",
    ""maps"": [
        {
            ""name"": ""QtePossibilities"",
            ""id"": ""cac7d18d-46c1-4a18-ac91-7e6b64ddb494"",
            ""actions"": [
                {
                    ""name"": ""qte_1"",
                    ""type"": ""Button"",
                    ""id"": ""cd19a8b2-db56-4652-b592-6692027a9435"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""qte_2"",
                    ""type"": ""Button"",
                    ""id"": ""bae1fa02-0f32-420e-8c0e-56c13be59a10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""qte_3"",
                    ""type"": ""Button"",
                    ""id"": ""51c16919-641b-4646-9588-e7f8c1e5568d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""qte_4"",
                    ""type"": ""Button"",
                    ""id"": ""c78f38fa-219b-4836-a842-52c6f9251f91"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""qte_5"",
                    ""type"": ""Button"",
                    ""id"": ""678ee4d2-46a3-4202-aa32-b22740ddc0c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""qte_6"",
                    ""type"": ""Button"",
                    ""id"": ""5972bfe4-db94-43b6-81b2-7a71a6133f78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""qte_7"",
                    ""type"": ""Button"",
                    ""id"": ""45127ccf-81f0-423e-ae03-96e906a73c13"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""qte_8"",
                    ""type"": ""Button"",
                    ""id"": ""5a065182-d7c2-4907-ac6d-e4594a7ba220"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""qte_9"",
                    ""type"": ""Button"",
                    ""id"": ""89c5cb90-f172-4bbb-ab28-19cb5e9facfd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""qte_10"",
                    ""type"": ""Button"",
                    ""id"": ""29fe942e-8d09-49af-a1b4-529670246e53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""qte_11"",
                    ""type"": ""Button"",
                    ""id"": ""2c8dd43d-8b27-480d-b653-f091ef554ed7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""qte_12"",
                    ""type"": ""Button"",
                    ""id"": ""d52865f9-3dcd-49c6-9dfb-c342ef576fdd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Randmize"",
                    ""type"": ""Button"",
                    ""id"": ""c0b8a784-5591-4c09-b893-28660b62f686"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d9ef5f49-c84a-4708-b8e1-c09025690677"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17936d4f-c6ef-42c6-943e-4a15fbe3f5bf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13d49160-5ced-4834-8727-b0b5077a21da"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a9f4aa0-7067-4e0b-b37d-3a3177c216c9"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5369fc9b-1815-4280-90c7-dda363cf0a79"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a9f011e-94cc-45fc-8bfc-afb3806af6a7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e9cdeba-1f0e-41d0-a70d-8baf26293dc1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15fd9a69-041a-4fa3-a81e-835f2d2ea85d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22a3114b-7bb2-4a67-b31b-531e01e27d1c"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55f7d567-80a3-4c7b-a3bf-9b3c6f8c61c4"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f73189c-c6a1-44eb-9c76-8b994691acf0"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_11"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b3eacfb-3a2b-45c1-91ef-771b7918981d"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""qte_12"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2a80dd1-fcb5-4a3b-a033-e25bb1f35361"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Randmize"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // QtePossibilities
        m_QtePossibilities = asset.FindActionMap("QtePossibilities", throwIfNotFound: true);
        m_QtePossibilities_qte_1 = m_QtePossibilities.FindAction("qte_1", throwIfNotFound: true);
        m_QtePossibilities_qte_2 = m_QtePossibilities.FindAction("qte_2", throwIfNotFound: true);
        m_QtePossibilities_qte_3 = m_QtePossibilities.FindAction("qte_3", throwIfNotFound: true);
        m_QtePossibilities_qte_4 = m_QtePossibilities.FindAction("qte_4", throwIfNotFound: true);
        m_QtePossibilities_qte_5 = m_QtePossibilities.FindAction("qte_5", throwIfNotFound: true);
        m_QtePossibilities_qte_6 = m_QtePossibilities.FindAction("qte_6", throwIfNotFound: true);
        m_QtePossibilities_qte_7 = m_QtePossibilities.FindAction("qte_7", throwIfNotFound: true);
        m_QtePossibilities_qte_8 = m_QtePossibilities.FindAction("qte_8", throwIfNotFound: true);
        m_QtePossibilities_qte_9 = m_QtePossibilities.FindAction("qte_9", throwIfNotFound: true);
        m_QtePossibilities_qte_10 = m_QtePossibilities.FindAction("qte_10", throwIfNotFound: true);
        m_QtePossibilities_qte_11 = m_QtePossibilities.FindAction("qte_11", throwIfNotFound: true);
        m_QtePossibilities_qte_12 = m_QtePossibilities.FindAction("qte_12", throwIfNotFound: true);
        m_QtePossibilities_Randmize = m_QtePossibilities.FindAction("Randmize", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // QtePossibilities
    private readonly InputActionMap m_QtePossibilities;
    private List<IQtePossibilitiesActions> m_QtePossibilitiesActionsCallbackInterfaces = new List<IQtePossibilitiesActions>();
    private readonly InputAction m_QtePossibilities_qte_1;
    private readonly InputAction m_QtePossibilities_qte_2;
    private readonly InputAction m_QtePossibilities_qte_3;
    private readonly InputAction m_QtePossibilities_qte_4;
    private readonly InputAction m_QtePossibilities_qte_5;
    private readonly InputAction m_QtePossibilities_qte_6;
    private readonly InputAction m_QtePossibilities_qte_7;
    private readonly InputAction m_QtePossibilities_qte_8;
    private readonly InputAction m_QtePossibilities_qte_9;
    private readonly InputAction m_QtePossibilities_qte_10;
    private readonly InputAction m_QtePossibilities_qte_11;
    private readonly InputAction m_QtePossibilities_qte_12;
    private readonly InputAction m_QtePossibilities_Randmize;
    public struct QtePossibilitiesActions
    {
        private @QTEInputActions m_Wrapper;
        public QtePossibilitiesActions(@QTEInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @qte_1 => m_Wrapper.m_QtePossibilities_qte_1;
        public InputAction @qte_2 => m_Wrapper.m_QtePossibilities_qte_2;
        public InputAction @qte_3 => m_Wrapper.m_QtePossibilities_qte_3;
        public InputAction @qte_4 => m_Wrapper.m_QtePossibilities_qte_4;
        public InputAction @qte_5 => m_Wrapper.m_QtePossibilities_qte_5;
        public InputAction @qte_6 => m_Wrapper.m_QtePossibilities_qte_6;
        public InputAction @qte_7 => m_Wrapper.m_QtePossibilities_qte_7;
        public InputAction @qte_8 => m_Wrapper.m_QtePossibilities_qte_8;
        public InputAction @qte_9 => m_Wrapper.m_QtePossibilities_qte_9;
        public InputAction @qte_10 => m_Wrapper.m_QtePossibilities_qte_10;
        public InputAction @qte_11 => m_Wrapper.m_QtePossibilities_qte_11;
        public InputAction @qte_12 => m_Wrapper.m_QtePossibilities_qte_12;
        public InputAction @Randmize => m_Wrapper.m_QtePossibilities_Randmize;
        public InputActionMap Get() { return m_Wrapper.m_QtePossibilities; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(QtePossibilitiesActions set) { return set.Get(); }
        public void AddCallbacks(IQtePossibilitiesActions instance)
        {
            if (instance == null || m_Wrapper.m_QtePossibilitiesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_QtePossibilitiesActionsCallbackInterfaces.Add(instance);
            @qte_1.started += instance.OnQte_1;
            @qte_1.performed += instance.OnQte_1;
            @qte_1.canceled += instance.OnQte_1;
            @qte_2.started += instance.OnQte_2;
            @qte_2.performed += instance.OnQte_2;
            @qte_2.canceled += instance.OnQte_2;
            @qte_3.started += instance.OnQte_3;
            @qte_3.performed += instance.OnQte_3;
            @qte_3.canceled += instance.OnQte_3;
            @qte_4.started += instance.OnQte_4;
            @qte_4.performed += instance.OnQte_4;
            @qte_4.canceled += instance.OnQte_4;
            @qte_5.started += instance.OnQte_5;
            @qte_5.performed += instance.OnQte_5;
            @qte_5.canceled += instance.OnQte_5;
            @qte_6.started += instance.OnQte_6;
            @qte_6.performed += instance.OnQte_6;
            @qte_6.canceled += instance.OnQte_6;
            @qte_7.started += instance.OnQte_7;
            @qte_7.performed += instance.OnQte_7;
            @qte_7.canceled += instance.OnQte_7;
            @qte_8.started += instance.OnQte_8;
            @qte_8.performed += instance.OnQte_8;
            @qte_8.canceled += instance.OnQte_8;
            @qte_9.started += instance.OnQte_9;
            @qte_9.performed += instance.OnQte_9;
            @qte_9.canceled += instance.OnQte_9;
            @qte_10.started += instance.OnQte_10;
            @qte_10.performed += instance.OnQte_10;
            @qte_10.canceled += instance.OnQte_10;
            @qte_11.started += instance.OnQte_11;
            @qte_11.performed += instance.OnQte_11;
            @qte_11.canceled += instance.OnQte_11;
            @qte_12.started += instance.OnQte_12;
            @qte_12.performed += instance.OnQte_12;
            @qte_12.canceled += instance.OnQte_12;
            @Randmize.started += instance.OnRandmize;
            @Randmize.performed += instance.OnRandmize;
            @Randmize.canceled += instance.OnRandmize;
        }

        private void UnregisterCallbacks(IQtePossibilitiesActions instance)
        {
            @qte_1.started -= instance.OnQte_1;
            @qte_1.performed -= instance.OnQte_1;
            @qte_1.canceled -= instance.OnQte_1;
            @qte_2.started -= instance.OnQte_2;
            @qte_2.performed -= instance.OnQte_2;
            @qte_2.canceled -= instance.OnQte_2;
            @qte_3.started -= instance.OnQte_3;
            @qte_3.performed -= instance.OnQte_3;
            @qte_3.canceled -= instance.OnQte_3;
            @qte_4.started -= instance.OnQte_4;
            @qte_4.performed -= instance.OnQte_4;
            @qte_4.canceled -= instance.OnQte_4;
            @qte_5.started -= instance.OnQte_5;
            @qte_5.performed -= instance.OnQte_5;
            @qte_5.canceled -= instance.OnQte_5;
            @qte_6.started -= instance.OnQte_6;
            @qte_6.performed -= instance.OnQte_6;
            @qte_6.canceled -= instance.OnQte_6;
            @qte_7.started -= instance.OnQte_7;
            @qte_7.performed -= instance.OnQte_7;
            @qte_7.canceled -= instance.OnQte_7;
            @qte_8.started -= instance.OnQte_8;
            @qte_8.performed -= instance.OnQte_8;
            @qte_8.canceled -= instance.OnQte_8;
            @qte_9.started -= instance.OnQte_9;
            @qte_9.performed -= instance.OnQte_9;
            @qte_9.canceled -= instance.OnQte_9;
            @qte_10.started -= instance.OnQte_10;
            @qte_10.performed -= instance.OnQte_10;
            @qte_10.canceled -= instance.OnQte_10;
            @qte_11.started -= instance.OnQte_11;
            @qte_11.performed -= instance.OnQte_11;
            @qte_11.canceled -= instance.OnQte_11;
            @qte_12.started -= instance.OnQte_12;
            @qte_12.performed -= instance.OnQte_12;
            @qte_12.canceled -= instance.OnQte_12;
            @Randmize.started -= instance.OnRandmize;
            @Randmize.performed -= instance.OnRandmize;
            @Randmize.canceled -= instance.OnRandmize;
        }

        public void RemoveCallbacks(IQtePossibilitiesActions instance)
        {
            if (m_Wrapper.m_QtePossibilitiesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IQtePossibilitiesActions instance)
        {
            foreach (var item in m_Wrapper.m_QtePossibilitiesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_QtePossibilitiesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public QtePossibilitiesActions @QtePossibilities => new QtePossibilitiesActions(this);
    public interface IQtePossibilitiesActions
    {
        void OnQte_1(InputAction.CallbackContext context);
        void OnQte_2(InputAction.CallbackContext context);
        void OnQte_3(InputAction.CallbackContext context);
        void OnQte_4(InputAction.CallbackContext context);
        void OnQte_5(InputAction.CallbackContext context);
        void OnQte_6(InputAction.CallbackContext context);
        void OnQte_7(InputAction.CallbackContext context);
        void OnQte_8(InputAction.CallbackContext context);
        void OnQte_9(InputAction.CallbackContext context);
        void OnQte_10(InputAction.CallbackContext context);
        void OnQte_11(InputAction.CallbackContext context);
        void OnQte_12(InputAction.CallbackContext context);
        void OnRandmize(InputAction.CallbackContext context);
    }
}
